# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Denobi
tagline:          'Portfolio'
description:      'Welcome to my portfolio! You can contant me in my Linkedin clicking <a href="https://www.linkedin.com/in/denobi/" target="_blank">here</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Denobi'
  url:            https://www.linkedin.com/in/denobi/

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/GustavoDenobi/GustavoDenobi.github.io
